---
title: "Covid19-vaccination in Japan"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(maps)
library(mapproj)
library(DT)
```

## 医療従事者
==============================================================

Column {data-width=60%}
-----------------------------------------------------------------------
### Map

```{r choropleths}


jpn.shp <- readRDS("gadm36_JPN_1_sp.rds")

vacc_dat <- read.csv("vacc.csv", fileEncoding = "UTF-8") %>% 
  slice(1:48)

va <- vacc_dat %>% mutate(NL_NAME_1=pref)
sp_data <- jpn.shp@data %>% 
  inner_join(va, by="NL_NAME_1") %>% 
  select(pref, vacc, vacc1, vacc2)

jpn.shp@data$pref <- sp_data$pref
jpn.shp@data$vacc <- sp_data$vacc
jpn.shp@data$vacc1 <- sp_data$vacc1
jpn.shp@data$vacc2 <- sp_data$vacc2

pal <- colorNumeric("YlOrRd", domain=jpn.shp@data$vacc, reverse=F)

labels <- sprintf("<strong>%s</strong><br/>接種回数：%5.0f<br/>内1回目：%5.0f<br/>内2回目：%5.0f",
                  paste0(jpn.shp@data$NL_NAME_1),
                  jpn.shp@data$vacc,
                  jpn.shp@data$vacc1,
                  jpn.shp@data$vacc2) %>% lapply(htmltools::HTML)

jpn.shp %>% 
  leaflet() %>% 
  setView(lat=37.5, lng=139, zoom=5) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(fillOpacity = 0.5,
              weight=1,
              fillColor = ~pal(jpn.shp@data$vacc),
              color = "orange",
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "16px",
                direction = "auto"),
              highlight = highlightOptions(
                weight = 5,
                color = "#888",
                fillOpacity = 0.5,
                bringToFront = TRUE)
              ) %>% 
  addLegend("bottomright", pal = pal, values = ~jpn.shp@data$vacc,
            title = "新型コロナウイルス<br/>ワクチン接種状況<br/>as of 21/05/2021"  )


```

Column {data-width=40%}
-----------------------------------------

### Table

```{r vacctination_table}


vacc_dat %>% 
  datatable(rownames=FALSE, 
            colnames=c("都道府県", "接種回数", "内1回目", "内2回目"),
            filter='top', 
            options=list(
              autoWidth=TRUE,
              pageLength=16
            )
          )

```

## 国民全体
==============================================================

Column {data-width=60%}
-----------------------------------------------------------------------
### Map

```{r choropleths_old}


jpn.shp <- readRDS("gadm36_JPN_1_sp.rds")

vacc_dat <- read.csv("vacc_civic.csv", fileEncoding = "UTF-8") %>% 
  slice(2:49)

va <- vacc_dat %>% mutate(NL_NAME_1=pref)
sp_data <- jpn.shp@data %>% 
  inner_join(va, by="NL_NAME_1") %>% 
  select(pref, vacc, vacc1, vacc2)

jpn.shp@data$pref <- sp_data$pref
jpn.shp@data$vacc <- sp_data$vacc
jpn.shp@data$vacc1 <- sp_data$vacc1
jpn.shp@data$vacc2 <- sp_data$vacc2

pal <- colorNumeric("YlOrRd", domain=jpn.shp@data$vacc, reverse=F)

labels <- sprintf("<strong>%s</strong><br/>接種回数：%5.0f<br/>内1回目：%5.0f<br/>内2回目：%5.0f",
                  paste0(jpn.shp@data$NL_NAME_1),
                  jpn.shp@data$vacc,
                  jpn.shp@data$vacc1,
                  jpn.shp@data$vacc2) %>% lapply(htmltools::HTML)

jpn.shp %>% 
  leaflet() %>% 
  setView(lat=37.5, lng=139, zoom=5) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(fillOpacity = 0.5,
              weight=1,
              fillColor = ~pal(jpn.shp@data$vacc),
              color = "orange",
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "16px",
                direction = "auto"),
              highlight = highlightOptions(
                weight = 5,
                color = "#888",
                fillOpacity = 0.5,
                bringToFront = TRUE)
              ) %>% 
  addLegend("bottomright", pal = pal, values = ~jpn.shp@data$vacc,
            title = "新型コロナウイルス<br/>ワクチン接種状況<br/>as of 14/08/2021"  )


```

Column {data-width=40%}
-----------------------------------------

### Table

```{r vacctination_table_old}


vacc_dat %>% 
  datatable(rownames=FALSE, 
            colnames=c("都道府県", "接種回数", "内1回目", "内2回目"),
            filter='top', 
            options=list(
              autoWidth=TRUE,
              pageLength=16
            )
          )

```

## 緊急搬送困難事案数
==============================================================

Column {data-width=60%}
-----------------------------------------------------------------------
### Map

```{r choropleths_emgergency}


jpn.shp <- readRDS("gadm36_JPN_1_sp.rds")

emerge_dat <- read.csv("emgergency.csv", fileEncoding = "UTF-8", header = TRUE) 

#emerge_dat <- read.csv("emgergency.csv", fileEncoding = "UTF-8", header = TRUE) %>% 
#  slice(2:8)

va <- emerge_dat %>% mutate(NL_NAME_1=pref)
sp_data <- jpn.shp@data %>% 
  inner_join(va, by="NL_NAME_1") %>% 
  select(pref, emergency)

jpn.shp@data$pref <- sp_data$pref
jpn.shp@data$emergency <- sp_data$emergency
#jpn.shp@data$vacc1 <- sp_data$vacc1

pal <- colorNumeric("YlOrRd", domain=jpn.shp@data$emergency, reverse=F)

labels <- sprintf("<strong>%s</strong><br/>事案数：%5.0f<br/>",
                  paste0(jpn.shp@data$NL_NAME_1),
                  jpn.shp@data$emergency) %>% lapply(htmltools::HTML)

jpn.shp %>% 
  leaflet() %>% 
  setView(lat=37.5, lng=139, zoom=5) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(fillOpacity = 0.5,
              weight=1,
              fillColor = ~pal(jpn.shp@data$emergency),
              color = "orange",
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "16px",
                direction = "auto"),
              highlight = highlightOptions(
                weight = 5,
                color = "#888",
                fillOpacity = 0.5,
                bringToFront = TRUE)
              ) %>% 
  addLegend("bottomright", pal = pal, values = ~jpn.shp@data$emergency,
            title = "新型コロナウイルス<br/>緊急搬送困難事案数<br/>as of 30/07/2021"  )


```

Column {data-width=40%}
-----------------------------------------

### Table

```{r vacctination_table_emerge}


emerge_dat %>% 
  datatable(rownames=FALSE, 
            colnames=c("都道府県", "緊急搬送困難事案数"),
            filter='top', 
            options=list(
              autoWidth=TRUE,
              pageLength=16
            )
          )

```
